import type { DiagramDocument } from "../types/diagram";

export function createExampleDiagram(): DiagramDocument {
  return {
    meta: {
      name: "Esempio Base",
      version: 1,
    },
    nodes: [
      { id: "student", type: "entity", label: "STUDENTE", x: 120, y: 220, width: 160, height: 64 },
      { id: "course", type: "entity", label: "CORSO", x: 470, y: 220, width: 140, height: 64 },
      {
        id: "teacher",
        type: "entity",
        label: "INSEGNANTE",
        x: 800,
        y: 220,
        width: 160,
        height: 64,
      },
      {
        id: "attends",
        type: "relationship",
        label: "FREQUENTA",
        x: 360,
        y: 100,
        width: 130,
        height: 78,
      },
      {
        id: "teaches",
        type: "relationship",
        label: "INSEGNA",
        x: 640,
        y: 340,
        width: 130,
        height: 78,
      },
      {
        id: "student-id",
        type: "attribute",
        label: "MATRICOLA",
        x: -20,
        y: 220,
        width: 150,
        height: 28,
        isIdentifier: true,
      },
      {
        id: "student-name",
        type: "attribute",
        label: "NOME",
        x: -20,
        y: 280,
        width: 150,
        height: 28,
      },
      {
        id: "course-id",
        type: "attribute",
        label: "CODICE",
        x: 510,
        y: 150,
        width: 150,
        height: 28,
        isIdentifier: true,
      },
      {
        id: "course-title",
        type: "attribute",
        label: "TITOLO",
        x: 510,
        y: 300,
        width: 160,
        height: 28,
      },
      {
        id: "teacher-id",
        type: "attribute",
        label: "ID_DOCENTE",
        x: 980,
        y: 220,
        width: 150,
        height: 28,
        isIdentifier: true,
      },
      {
        id: "teacher-name",
        type: "attribute",
        label: "NOME",
        x: 980,
        y: 280,
        width: 150,
        height: 28,
      },
    ],
    edges: [
      {
        id: "e1",
        type: "connector",
        sourceId: "attends",
        targetId: "student",
        label: "",
        lineStyle: "solid",
        cardinality: "(0,N)",
      },
      {
        id: "e2",
        type: "connector",
        sourceId: "attends",
        targetId: "course",
        label: "",
        lineStyle: "solid",
        cardinality: "(1,N)",
      },
      {
        id: "e3",
        type: "connector",
        sourceId: "teaches",
        targetId: "teacher",
        label: "",
        lineStyle: "solid",
        cardinality: "(0,N)",
      },
      {
        id: "e4",
        type: "connector",
        sourceId: "teaches",
        targetId: "course",
        label: "",
        lineStyle: "solid",
        cardinality: "(1,1)",
      },
      { id: "e5", type: "attribute", sourceId: "student-id", targetId: "student", label: "", lineStyle: "solid" },
      { id: "e6", type: "attribute", sourceId: "student-name", targetId: "student", label: "", lineStyle: "solid" },
      { id: "e7", type: "attribute", sourceId: "course-id", targetId: "course", label: "", lineStyle: "solid" },
      { id: "e8", type: "attribute", sourceId: "course-title", targetId: "course", label: "", lineStyle: "solid" },
      { id: "e9", type: "attribute", sourceId: "teacher-id", targetId: "teacher", label: "", lineStyle: "solid" },
      { id: "e10", type: "attribute", sourceId: "teacher-name", targetId: "teacher", label: "", lineStyle: "solid" },
    ],
  };
}
