import type { DiagramDocument } from "../types/diagram";

export function createExampleDiagram(): DiagramDocument {
  return {
    meta: {
      name: "Esempio Chen",
      version: 1,
    },
    nodes: [
      { id: "city", type: "entity", label: "CITTA'", x: 140, y: 220, width: 140, height: 64 },
      { id: "person", type: "entity", label: "PERSONA", x: 560, y: 80, width: 140, height: 64 },
      { id: "man", type: "entity", label: "UOMO", x: 430, y: 250, width: 140, height: 64 },
      { id: "woman", type: "entity", label: "DONNA", x: 690, y: 250, width: 140, height: 64 },
      { id: "soldier", type: "entity", label: "MILITARE", x: 430, y: 430, width: 140, height: 64 },
      {
        id: "worker",
        type: "entity",
        label: "LAVORATRICE",
        x: 690,
        y: 430,
        width: 160,
        height: 64,
      },
      {
        id: "resides",
        type: "relationship",
        label: "RESIEDE",
        x: 360,
        y: 120,
        width: 130,
        height: 78,
      },
      { id: "born-m", type: "relationship", label: "NATO", x: 300, y: 260, width: 130, height: 78 },
      { id: "born-f", type: "relationship", label: "NATA", x: 510, y: 340, width: 130, height: 78 },
      {
        id: "service",
        type: "relationship",
        label: "FA SERVIZIO",
        x: 240,
        y: 440,
        width: 150,
        height: 84,
      },
      { id: "name", type: "attribute", label: "NOME", x: 780, y: 80, width: 150, height: 28 },
      {
        id: "surname",
        type: "attribute",
        label: "COGNOME",
        x: 780,
        y: 130,
        width: 150,
        height: 28,
      },
      { id: "age", type: "attribute", label: "ETA'", x: 780, y: 180, width: 150, height: 28 },
      {
        id: "height",
        type: "attribute",
        label: "ALTEZZA",
        x: 410,
        y: 210,
        width: 150,
        height: 28,
      },
      {
        id: "province",
        type: "attribute",
        label: "PROVINCIA",
        x: -40,
        y: 220,
        width: 160,
        height: 28,
      },
      {
        id: "region",
        type: "attribute",
        label: "REGIONE",
        x: -40,
        y: 280,
        width: 150,
        height: 28,
      },
      {
        id: "note",
        type: "text",
        label: "Gerarchia Chen con specializzazioni",
        x: 480,
        y: 16,
        width: 280,
        height: 24,
      },
    ],
    edges: [
      { id: "e1", type: "connector", sourceId: "resides", targetId: "city", label: "", lineStyle: "solid" },
      { id: "e2", type: "connector", sourceId: "resides", targetId: "person", label: "", lineStyle: "solid" },
      { id: "e3", type: "connector", sourceId: "born-m", targetId: "city", label: "", lineStyle: "solid" },
      { id: "e4", type: "connector", sourceId: "born-m", targetId: "man", label: "", lineStyle: "solid" },
      { id: "e5", type: "connector", sourceId: "born-f", targetId: "city", label: "", lineStyle: "solid" },
      { id: "e6", type: "connector", sourceId: "born-f", targetId: "woman", label: "", lineStyle: "solid" },
      { id: "e7", type: "connector", sourceId: "service", targetId: "city", label: "", lineStyle: "solid" },
      { id: "e8", type: "connector", sourceId: "service", targetId: "soldier", label: "", lineStyle: "solid" },
      { id: "e9", type: "attribute", sourceId: "name", targetId: "person", label: "", lineStyle: "solid" },
      { id: "e10", type: "attribute", sourceId: "surname", targetId: "person", label: "", lineStyle: "solid" },
      { id: "e11", type: "attribute", sourceId: "age", targetId: "person", label: "", lineStyle: "solid" },
      { id: "e12", type: "attribute", sourceId: "height", targetId: "man", label: "", lineStyle: "solid" },
      { id: "e13", type: "attribute", sourceId: "province", targetId: "city", label: "", lineStyle: "solid" },
      { id: "e14", type: "attribute", sourceId: "region", targetId: "city", label: "", lineStyle: "solid" },
      { id: "e15", type: "inheritance", sourceId: "man", targetId: "person", label: "", lineStyle: "solid" },
      { id: "e16", type: "inheritance", sourceId: "woman", targetId: "person", label: "", lineStyle: "solid" },
      { id: "e17", type: "inheritance", sourceId: "soldier", targetId: "man", label: "", lineStyle: "solid" },
      { id: "e18", type: "inheritance", sourceId: "worker", targetId: "woman", label: "", lineStyle: "solid" },
    ],
  };
}
